services:
  # Frontend Service (Next.js)
  - type: web
    name: hackforge-frontend
    env: node
    plan: starter
    runtime: node20
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: hackforge-backend
          property: host
      - key: NEXT_PUBLIC_SITE_URL
        value: https://hackforge-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true
    
  # Backend Service (Node.js/Express)
  - type: web
    name: hackforge-backend
    env: node
    plan: starter
    runtime: node20
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        fromService:
          type: web
          name: hackforge-frontend
          property: host
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: hackforge-redis
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true
    
  # Redis Cache Service
  - type: redis
    name: hackforge-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList:
      - source: 0.0.0.0/0
        description: Allow all connections

# Database (if using PostgreSQL instead of MongoDB)
# - type: pserv
#   name: hackforge-postgres
#   env: postgres
#   plan: starter
#   databases:
#     - name: hackforge_db
#       user: hackforge_user
