services:
  # Frontend Service (Next.js)
  - type: web
    name: hackforge-frontend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://hackforge-backend.onrender.com
      - key: NEXT_PUBLIC_SITE_URL
        value: https://hackforge-frontend.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Backend Service (Node.js/Express)
  - type: web
    name: hackforge-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://hackforge-frontend.onrender.com
      - key: MONGODB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: REDIS_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true

  # Redis Cache Service (Optional)
  - type: redis
    name: hackforge-redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    # autoDeploy: false
